/// Centralized API configuration — swap these for your own keys.
class ApiConfig {
  ApiConfig._();

  // Stream Chat — get from https://getstream.io/dashboard
  static const String streamApiKey = 'urj88zxegfw8';

  // Backend server URL — replace with your Render URL after deploy
  // Example: https://planmate-backend.onrender.com
  static const String backendUrl = 'http://localhost:8000';

  // Firebase project config is in firebase_options.dart (generated by flutterfire)
  // See: https://firebase.google.com/docs/flutter/setup
}
