/// Centralized API configuration — swap these for your own keys.
class ApiConfig {
  ApiConfig._();

  // Stream Chat — get from https://getstream.io/dashboard
  static const String streamApiKey = 'urj88zxegfw8';

  // Backend server URL — your Render deployment
  static const String backendUrl = 'https://planmate-app.onrender.com';

  // Firebase project config is in firebase_options.dart (generated by flutterfire)
  // See: https://firebase.google.com/docs/flutter/setup
}
